### ISSUE TITLE
Connection Refused 127.0.0.1:26657

### ISSUE THREAD

**Issue by trizzle5k** [CoreumFoundation/coreum#124]
Connections to tendermint is being refused. Picture attached for details. 
![B6E5E4A9-BCC4-4301-A176-A74F93CD0863](https://user-images.githubusercontent.com/10102816/183096857-b2cfe06e-93c9-4390-b588-9d1528c00da5.jpeg)

**Comment by wojtek-coreum** [comment]
@trizzle5k 

Please take a look at the list of containers in docker by running `docker ps -a`.
Check if container called `znet-coredev-00` is running, I guess it exited for some reason.

If this is true please take a look at its logs: `docker logs znet-coredev-00` and if there are errors, please post them here.

**Comment by trizzle5k** [comment]
![image](https://user-images.githubusercontent.com/10102816/183425791-8e4b26f2-3f92-4f2d-b089-6f9113564a50.png)

![image](https://user-images.githubusercontent.com/10102816/183425567-d83dddcb-3d51-462a-984a-b53c47430d3d.png)

**Comment by wojtek-coreum** [comment]
I see. You have two repositories checked out in your directory: `coreum` and `crust`.
Please be sure that you pulled the latest master in both of them.

Then run these commands:
```
$ crust znet remove # to be shure that you don't have any stale docker containers and files from previous deployments
$ crust build/cored build/znet # to rebuild binaries from fresh pulled master
$ crust znet start
```

**Comment by trizzle5k** [comment]
Looks like there was a problem with the coreum repo. Deployed successfully, thank you!
