### ISSUE TITLE
`hermes` fails to import account created by `cored`

### ISSUE THREAD

**Issue by 99Kies** [CoreumFoundation/coreum#731]
### What happened?

I need to create a relayer with coreum, but I'm having this problem when importing a coreum account using hermes.

### What did you expect to happen?

hermes will successfully import coreum's account

### Steps to reproduce the behavior (as precisely as possible)

1. use cored to create account.
```bash
cored keys add keycoreum --output json > keycoreum.json
```

2. import this account to hermes.
```bash
hermes keys add --chain coreum-mainnet-1 --key-file keycoreum.json
```

### Versions (please complete the following information)

cored v3.0.0

### Logs

error message
```
➜  relayer-keys hermes keys add --chain coreum-mainnet-1 --key-file keycoreum.json
2023-11-29T14:32:04.597459Z  INFO ThreadId(01) using default configuration from '/home/ubuntu/.hermes/config.toml'
2023-11-29T14:32:04.598236Z  INFO ThreadId(01) running Hermes v1.7.2
ERROR An error occurred adding the key on chain coreum-mainnet-1 from file "keycoreum.json": mismatch between the public key in the key file and the public key in the mnemonic
```

### Screenshots

<details>

</details>

### Anything else we need to know?

<details>

</details>

**Comment by dzmitryhil** [comment]
By default the coreum uses 990 coin type, which is not default for the hermes, so you need to provide the hermes the hd-path flag with correctly set coin type: 
--hd-path "m/44'/990'/0'/0/0"

**Comment by 99Kies** [comment]
yeah,`hermes keys add --chain coreum-mainnet-1 --key-file keycoreum.json --hd-path "m/44'/990'/0'/0/0"`
