### ISSUE TITLE
Forking the Coreum NFT implementation

### ISSUE THREAD

**Issue by Tectract** [CoreumFoundation/coreum#810]
### What happened?

Sorry this is not a bug report, but a question. We are hoping to fork the Coreum NFT implementation, and I was wondering if there is more than just the x/nft folder that we need, like maybe the x/wnft folder also? We are also hoping to see a more functional nft codebase pulled into the core cosmos repository, have you guys considered making a PR to get your code pulled upstream, to their repo?

### What did you expect to happen?

-

### Steps to reproduce the behavior (as precisely as possible)

-

### Versions (please complete the following information)

- Full OS version: [e.g. macOS 12.0.1]
- Docker version: (you can get it by executing `docker version`)
- Coreum & crust git commit sha: (you can get it by executing `git rev-parse --short HEAD` in an appropriate repo)
- Other (if applicable)

### Logs

<details>

```console
```

</details>

### Screenshots

<details>

</details>

### Anything else we need to know?

<details>

</details>

**Comment by keyleu** [comment]
Hey there @Tectract.

Regarding x/nft and x/wnft:

1) x/nft is the standard x/nft module that is already in the Cosmos SDK.

2) Additionally, we have the x/asset/nft module which adds a lot of extra functionality to the NFTs, including the features that are described in the spec (whitelisting, freezing, ...). the /x/wnft module is a wrapper around the nft module to intercept the messages sent to make these features possible. So if you want to fork and have the full functionality of our NFTs then you need to include not only x/wnft but also the /x/asset/nft module. If you also want this functionality in smart contracts you need to have the wasm module logic as well.

Regarding upstreaming this to the cosmos repository, there are no plans for doing this as these modules are particular to the Coreum blockchain and our use-cases.
